// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var $compass, prevHeading;
    $compass = $('#compass');
    prevHeading = null;
    return $(window).on('deviceorientation', function(e) {
      var heading, msg;
      heading = Math.round(e.webkitCompassHeading);
      if (e.webkitCompassHeading !== 0 && heading !== prevHeading) {
        $compass.css({
          '-webkit-transform': "rotate(-" + e.webkitCompassHeading + "deg)"
        });
        msg = new Message();
        msg.address = '/compass';
        msg.addFloat(e.webkitCompassHeading);
        msg.send();
        return prevHeading = heading;
      }
    });
  });

}).call(this);
