// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var touchPointSize;
    touchPointSize = 50;
    return $(document).on('tap', '.draggable', function(e) {
      return $(this).toggleClass('active');
    }).on('touchmove', '.draggable', function(e) {
      var msg;
      e.target.style.left = "" + (e.touches[0].pageX - touchPointSize / 2) + "px";
      e.target.style.top = "" + (e.touches[0].pageY - touchPointSize / 2) + "px";
      msg = new Message('/position');
      msg.addInt(e.touches[0].pageX);
      msg.addInt(e.touches[0].pageY);
      return msg.send();
    });
  });

}).call(this);
