// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $('.button').on('touchstart', function(e) {
      return $(this).addClass('touched');
    }).on('touchend', function(e) {
      var msg;
      if ($(this).is('.touched')) {
        msg = new Message('/run-program');
        msg.addInt(parseInt($(this).data('program'), 10));
        return msg.send();
      }
    }).on('touchend touchmove', function(e) {
      return $(this).removeClass('touched');
    });
  });

}).call(this);
